
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/anujb/Downloads/cmake-3.28.1/cmake-3.28.1/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
